version: '3.8'

services:
  # Next.js Application with SQLite
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html5
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  app-network:
    driver: bridge
