version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
      - "1337:1337"
    volumes:
      - ./:/srv/app
      - ./tmp:/srv/app/.tmp
      - ./public:/srv/app/public
    environment:
      - NODE_ENV=production
